### ISSUE TITLE
CLI interface design

### ISSUE THREAD

**Issue by samhh** [samhh/terpod#1]
### Syncing

- [x] `$ terpod sync`
- [ ] `$ terpod sync <podcast-id>`
- [ ] `$ terpod sync <podcast-id>,<podcast-id>,<...>`

### Listing

It'd probably be nice to display more info e.g. description, filesize.

- [x] `$ terpod list`
- [x] `$ terpod list <podcast-id>`
- [ ] `$ terpod list <podcast-id>,<podcast-id>,<...>`
- [x] Flags: `--oldest`, `--offset`, `--limit`

### Downloading

- [x] `$ terpod download <podcast-id> <episode-id>`
    - [ ] Might be nice if you can provide a file name?
- [ ] `$ terpod download <podcast-id> <episode-id>,<episode-id>,<...>`

### Playing

Probably best if it just outputs the path and leaves playing to other apps?

### Deleting

Useful?

**Comment by samhh** [comment]
N.B. There could be collisions between `<id>,<id>` syntax and IDs that contain commas.
